### PR TITLE
Adding results for measurements on HZDR's hemera cluster.

### PR DESCRIPTION
**Pull request by zyzzyxdonta**
Hi!

Here are my FFTW 3.3.8 measurements from HZDR's hemera cluster (Xeon Gold 6148 Skylake CPUs). 1D extents with `--rigor measure` are not done, yet.

### CODE REVIEW

**Comment by psteinb** [comment]
lovely, thanks!

**Comment by psteinb** [comment]
once, the WIP has disappeared, I'll merge.

**Comment by zyzzyxdonta** [comment]
I had to use a configuration with fewer extents as to not exceed the allowed 96 hours on hemera. So I used the extents_1d_fftw.conf file.

Should I squash the commits?

**Comment by psteinb** [comment]
feel free to squash the commits, sure.

**Comment by psteinb** [comment]
I'll merge this now. We should contemplate documenting that splitting the input file can be done with no harm. Merging the results is a more tricky thing due to the CSV headers.

**Comment by zyzzyxdonta** [comment]
OK, so the results are basically worthless because AVX512 support in FFTW is broken. See https://github.com/FFTW/fftw3/issues/143
Feel free to revert the merge.

**Comment by psteinb** [comment]
For me personally, this is an interesting finding! I think we should keep it in due hope, that the performance of fftw will
improve on AVX512 in an upstream version. Would you have the possibility to conduct runs with the Intel MKL's fftw interface on
Skylake and above?

**Comment by zyzzyxdonta** [comment]
After posting that comment I realized I hadn't even built with AVX512 support. I took the script from the gearshifft readme which was SSE2 only. I can redo it with AVX and AVX2 enabled. MKL is also possible.

**Comment by psteinb** [comment]
Go for it! I expect that the AVX512 are on par with plain AVX/AVX2.

**Pull request merged**
