### PR TITLE
Skylake AVX2 and MKL

### PR DESCRIPTION
**Pull request by zyzzyxdonta**
I'm going to add gearshifft measurements with AVX2 on Skylake. 

Also, in #13 @psteinb asked for MKL measurements. I'm working on it but the job failed overnight due to integer divisions by zero for FFT sizes 3^19 and 5^13. These divisions occur in an MKL function called `commit`. I tried a little toy program with dynamically linked MKL and it works fine. I didn't check statically linked, yet. Maybe I can reproduce the error that way.

### CODE REVIEW

**Comment by psteinb** [comment]
Let me know, once you feel safe about these results.

**Comment by psteinb** [comment]
Let me know, once you feel safe about these results.

**Comment by zyzzyxdonta** [comment]
I was able to reproduce the bug in MKL. I messaged our IT department about it and asked them to get in touch with Intel. Contacting Intel directly was of course not possible for me.

For reference, I attached the source code for my test program. (Wow, GitHub uses file extensions to decide which files can be uploaded 😂)
[mkl-test.zip](https://github.com/mpicbg-scicomp/gearshifft_results/files/5509744/mkl-test.zip)

**Comment by zyzzyxdonta** [comment]
The data looks plausible through the rshiny app. This can be merged!

**Pull request merged**
