### PR TITLE
Adding results

### PR DESCRIPTION
**Pull request by bkmgit**
Adding some results from running the benchmark

### CODE REVIEW

**Comment by tdd11235813** [comment]
ok, results seems to be fine (see pictures below, red lines are your measurements)

Total Time (compared to broadwell + fftw 3.3.6pl1):
fftw-i5
FFT Time (compared to broadwell + fftw 3.3.6pl1):
fftw-i5-fft

- are these the extents you have been interested in? Just asking because there are only few selected extents benchmarked
- if you want to add further results, you can add these to this PR
- for merging, we would like to have these commits squashed into one commit
```bash
git rebase -i HEAD~3
# mark the last two commits with "squash"
# then give a commit message like "Adds results for fftw3.3.8 (measure, gcc8.1.1, fedora28)."
```
- for merging the results file should end with `.csv` (rshiny scripts relies on that)
- for playing around you can [go here](https://www.kcod.de/gearshifft/) (your results have been uploaded there. Tag with fftw, then last entry)

**Comment by bkmgit** [comment]
Expect to add a few more results using other libraries in the next week or so. Full benchmark can take a long time to run. At the expense of less accurate error bars, may want measurements complete in a few minutes, to at most an hour on a single processor. Also unclear how to have proper file naming procedure.

**Comment by tdd11235813** [comment]
No problem, more extensive benchmarks are welcome :)
A suggestion for file naming (example is for 1D FFT extents):
```
results/bkmgit-intel-i5-6200/fftw3.3.8/fftw_measure_gcc8.1.1_fedora28.1d.csv
```

**Comment by bkmgit** [comment]
Added a few more results using the small test suite. Extended 1D case to be added soon.

**Comment by psteinb** [comment]
Hey @bkmgit, can you mark this PR as WIP, please? This way we know, when to review it for merging ... namely once you remove the WIP in the title.

**Comment by bkmgit** [comment]
It seems unlikely will add more in the near future. Let me know if they all need to be squashed into one commit, this seems not to happen very cleanly.

**Comment by bkmgit** [comment]
Made new pull request.

**Pull request closed without merging**
