### PR TITLE
Mkl gnu wrappers

### PR DESCRIPTION
**Pull request by psteinb**
AFAIK, float16 is not supported by the wrappers as it is not supported by fftw.

### CODE REVIEW

**Comment by tdd11235813** [comment]
I have added them to the [online viewer](https://www.kcod.de/gearshifft/), you can compare and you can merge your PR, if you want to.
Few notes:
- fftw backend does not provide CPU hardware details, so `CPU` is only shown in the diagram
  - you can set a label for the curve manually and name the CPU architecture (e.g. MKL on broadwell)
- MKL is faster, but this can be due to broadwell/haswell differences or 40 cores vs 24 cores (single-cpu would be interesting, too), different clock rates, or due to better implementation?

**Comment by psteinb** [comment]
the online viewer is missing the haswell MKL results as far as I can tell. Please add them today.

**Comment by psteinb** [comment]
but in general, I agree with your comments. We need to consolidate the data and potentially reflect that in scripts which come with the results. Now that fftw 3.3.8 is out, it would be a good chance to renew the fftw numbers.

**Comment by tdd11235813** [comment]
oops, I only added broadwell, sorry. Now haswell MKL is online, too. Also added tags for filtering, PR will come next days, if not needed tomorrow.

**Comment by psteinb** [comment]
thanks, that makes things somewhat more clear. send PR when you are ready.

**Pull request merged**
