### PR TITLE
Change directory layout

### PR DESCRIPTION
**Pull request by zyzzyxdonta**
@psteinb

### CODE REVIEW

**Comment by psteinb** [comment]
Does this PR now introduce your thesis results into the online visualisation?

**Comment by zyzzyxdonta** [comment]
I have no access to the current online visualizer and the visualizer @ HZDR is not yet set up due to admininistrative reasons. When deploying the app, the results directory has to be placed into the rshiny directory so that the app finds the csv files automatically, just like it was before.

**Comment by psteinb** [comment]
Ok, feel free to try the visualizer locally and check if it works to some degree.

**Comment by zyzzyxdonta** [comment]
I tried that and it works except for some ~~warnings~~ infos from R/R-shiny which I don't understand because I've never worked with R:

```
── Column specification ────────────────────────────────────────────────────────
cols(
  .default = col_double(),
  library = col_character(),
  inplace = col_character(),
  complex = col_character(),
  precision = col_character(),
  kind = col_character(),
  success = col_character()
)
ℹ Use `spec()` for the full column specifications.

1 Time_Total -> succeeded[,21] in Time_Total 
[ylabel] using ylabel:  Time Total [ms] 
`summarise()` regrouping output by 'library', 'inplace', 'complex', 'precision', 'dim', 'kind', 'nx', 'ny', 'nz', 'Error_StandardDeviation', 'Error_Mismatches', '.file_id', 'n_elements', 'nbytes', 'hardware', 'architecture', 'xmoi' (override with `.groups` argument)
```

Othen than that the newly added architectures are not supported as tags yet in this section:
Screenshot_20210128_144642

I can try to add them but that would require digging a bit into the code because I've never done anything in R before.

**Comment by psteinb** [comment]
Great to see that. Yeah, the _informations_ can be ignored. If you could look into the tags, that would be wonderful. But don't get fed up into learning `R`. If you find yourself doing so, we'll go ahead and merge.

**Comment by zyzzyxdonta** [comment]
Alright, I'll look into it

**Comment by zyzzyxdonta** [comment]
I refined the tags a bit in 0312fd4982e9e5ac05b67b94a026b9de7562981c
Screenshot_20210209_110521

I think a bit of cleanup and refactoring would still be nice as there are a lot of code duplications

**Comment by psteinb** [comment]
Great Work! That looks superb. I think we should manage now.

**Pull request merged**
